# Generated by Django 4.0.4 on 2022-04-15 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('modifytime', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('title', models.CharField(help_text='话题', max_length=255)),
                ('content', models.TextField(help_text='内容')),
                ('user', models.ForeignKey(help_text='用户名', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('modifytime', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('comment', models.TextField(help_text='评论')),
                ('up', models.IntegerField(default=0, help_text='点赞')),
                ('down', models.IntegerField(default=0, help_text='踩')),
                ('topic_title', models.ForeignKey(help_text='话题', on_delete=django.db.models.deletion.CASCADE, to='post.topic')),
                ('user', models.ForeignKey(help_text='用户名', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
